name: mirzagram-prod
services:
  db:
    container_name: mirzagram-db-prod
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: mirzagram-db
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: mirza
    networks:
      - mirza-net-prod
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d mirzagram-db -U mirza"]
      interval: 20s
      timeout: 5s
      retries: 5
    restart: on-failure

  api:
    container_name: mirzagram-api-prod
    env_file:
      - ./backend/.env.prod
    ports:
      - 81:3000
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - mirza-net-prod
    depends_on:
      db:
        condition: service_healthy
    stdin_open: true
    tty: true

  front:
    container_name: mirzagram-front-prod

    ports:
      - 80:80
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - BUILD_MODE=prod
    networks:
      - mirza-net-prod
    depends_on:
      - api

  nginx:
    container_name: mirzagram-nginx-prod
    ports:
      - 443:443
    build:
      context: ./nginx
      dockerfile: Dockerfile
    networks:
      - mirza-net-prod
    volumes:
      - /etc/letsencrypt/live/shapshoop.store
    depends_on:
      - front

networks:
  mirza-net-prod:
    driver: bridge
