name: mirzagram-prod
services:
  db:
    container_name: mirzagram-db-prod
    image: postgres
    environment:
      POSTGRES_DB: mirzagram-db
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: mirza
    networks:
      - mirza-net-prod

  api:
    container_name: mirzagram-api-prod
    env_file:
      - ./backend/.env.prod
    ports:
      - 81:3000
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - mirza-net-prod
    depends_on:
      - db
    stdin_open: true
    tty: true

  front:
    container_name: mirzagram-front-prod
    environment:
      VITE_REACT_APP_BASE_URL: http://37.32.6.153:81/
    ports:
      - 80:80
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - mirza-net-prod
    depends_on:
      - api

  nginx:
    container_name: mirzagram-nginx-prod
    ports:
      - 443:443
    build:
      context: ./nginx
      dockerfile: Dockerfile
    networks:
      - mirza-net-prod
    volumes:
      - /etc/letsencrypt/live/shapshoop.store
    depends_on:
      - front

networks:
  mirza-net-prod:
    driver: bridge
