name: mirzagram-prod
services:
  db:
    container_name: mirzagram-db-prod
    image: postgres
    environment:
      POSTGRES_DB: mirzagram-db
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: mirza
    networks:
      - mirza-net-prod
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -d mirzagram-db -U mirza"]
    #   interval: 20s
    #   timeout: 5s
    #   retries: 5
    # restart: on-failure
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  api:
    image: registry.hamdocker.ir/mirzap/mirzagram-api:${VERSION}
    container_name: mirzagram-api-prod
    env_file:
      - ./backend/.env.prod
    ports:
      - 81:3000
    networks:
      - mirza-net-prod
    depends_on:
      - db
    stdin_open: true
    tty: true
    volumes:
      - ./storage:/app/uploads

  front:
    image: registry.hamdocker.ir/mirzap/mirzagram-front:${VERSION}
    container_name: mirzagram-front-prod
    # environment:
      # VITE_REACT_APP_BASE_URL: http://37.32.6.153:81/
    ports:
      - 80:80
    networks:
      - mirza-net-prod
    depends_on:
      - api

  nginx:
    container_name: mirzagram-nginx-prod
    ports:
      - 443:443
    build:
      context: ./nginx
      dockerfile: Dockerfile
    networks:
      - mirza-net-prod
    volumes:
      - /etc/letsencrypt/live/mirza-penguin.dev1403.rahnemacollege.ir/fullchain.pem:/etc/letsencrypt/live/mirza-penguin.dev1403.rahnemacollege.ir/fullchain.pem
      - /etc/letsencrypt/live/mirza-penguin.dev1403.rahnemacollege.ir/privkey.pem:/etc/letsencrypt/live/mirza-penguin.dev1403.rahnemacollege.ir/privkey.pem
    depends_on:
      - front

networks:
  mirza-net-prod:
    driver: bridge
