/* eslint @typescript-eslint/naming-convention: 0 */

export const strings = {
  BAD_REQUEST_ERROR: "درخواست نامعتبر است",
  INTERNAL_SERVER_ERROR: "خطای داخلی سرور",
  INVALID_EMAIL_ERROR: "ایمیل نامعتبر است",
  INVALID_PASSWORD_ERROR: "پسورد نامعتبر است",
  INVALID_USERNAME_ERROR: "نام کاربری نامعتبر است",
  INVALID_URL_ERROR: "آدرس منبع نامعتبر است",
  CREATE_USER_SUCCESSFUL: "حساب کاربری با موفقیت ساخته شد",
  SIGNIN_USER_SUCCESSFUL: "ورود به حساب با موفقیت انجام شد",
  SEND_RESET_PASSWORD_LINK_SUCCESSFUL:
    "لینک فراموشی رمزعبور با موفقیت ارسال شد",
  RESET_PASSWORD_SUCCESSFUL: "رمزعبور با موفقیت تغییر کرد",
  UPDAT_PROFILE_SUCCESSFUL: "پروفایل با موفقیت به روز رسانی شد",
  PASSWORDS_DO_NOT_MATCH_ERROR: "رمزعبور و تکرار آن یکسان نیست",
  INVALID_USERNAME_OR_PASSWORD_ERROR: "نام کاربری یا رمزعبور اشتباه است",
  RESET_PASSWORD_TOKEN_EXPIRED_ERROR: "توکن منقضی شده است",
  EMAIL_ALREADY_EXISTS_ERROR: "ایمیل تکراری است",
  USERNAME_ALREADY_EXISTS_ERROR: "نام کاربری تکراری است",
  USER_NOT_FOUND: "کاربر یافت نشد",
  FILE_NOT_FOUND: "فایل یافت نشد",
  FILE_UPLOAD_SUCCESSFUL: "فایل با موفقیت آپلود شد",
  POST_ADDED_SUCCESSFULLY: "پست با موفقیت اضافه شد",
  POST_EDITED_SUCCESSFULLY: "پست با موفقیت ویرایش شد",
  POST_NOT_FOUND_ERROR: "پست پیدا نشد",
  FILE_NAME_EMPTY_ERROR: "نام فایل نمیتواند خالی باشد",
  CANNOT_ADD_POST_FOR_PROFILE_ERROR: "این پروفایل امکان افزودن عکس را ندارد",
  POST_FORBIDDEN_ERROR: "شما به این پست دسترسی ندارید",
  MENTION_USERNAME_NOT_EXIST_ERROR: "نام کاربری منشن شده وجود ندارد",
  MENTION_EMPTY_ERROR: "منشن وارد شده خالی است",
  POST_MUST_HAVE_PHOTO_ERROR: "پست نمیتواند بدون عکس باشد",
  FOLLOWED_SUCCESSFULLY: "دنبال کردن کاربر با موفقیت انجام شد",
  UNFOLLOWED_SUCCESSFULLY: "حذف دنبال کردن کاربر با موفقیت انجام شد",
  USER_IS_NOT_FOLLOWED: "کاربر دنبال نشده است",
  USER_IS_ALREADY_FOLLOWED: "کاربر قبلا فالو شده است",
  FOLLOWER_AND_FOLLOWING_IS_SAME: "دنبال کننده و دنبال شونده برابر است",
  INVALID_FOLLOW_REQUEST_STATUS: "وضعیت درخواست دنبال کردن نامعتبر است",
  FOLLOW_REQUEST_IS_ALREADY_SENT: "درخواست دنبال کردن قبلا ارسال شده است",
  FOLLOW_REQUEST_NOT_FOUND: "درخواست دنبال کردن یافت نشد",
  FOLLOW_REQUEST_SENT: "درخواست دنبال کردن ارسال شد",
  HAVE_NOT_ANY_FOLLOW_REQUEST: "شما هیچ درخواست دنبال کردنی ندارید",
  FOLLOW_REQUEST_CANCELED: "درخواست دنبال کردن لغو شد",
  FOLLOW_REQUEST_REJECTED: "درخواست دنبال کردن رد شد",
  FOLLOW_REQUEST_ACCEPTED: "درخواست دنبال کردن قبول شد",
  USER_IS_ALREADY_CLOSE_FRIEND: "کاربر قبلا به عنوان دوست نزدیک اضافه شده است",
  CLOSE_FRIEND_ADDED: "کاربر به عنوان دوست نزدیک اضافه شد",
  CLOSE_FRIEND_REMOVED: "کاربر از دوستان نزدیک حذف شد",
  NO_CLOSE_FRIENDS: "دوست نزدیکی وجود ندارد",
  USER_IS_BLOCKED: "کاربر مسدود شده است",
  PROFILE_BLOCKED: "پروفایل مسدود شد",
  PROFILE_UNBLOCKED: "پروفایل آزاد شد",
  COMMENT_ADDED_SUCCESSFULLY: "کامنت با موفقیت اضافه شد",
  COMMENT_TEXT_CANNOT_BE_EMPTY_ERROR: "متن کامنت نمیتواند خالی باشد",
  POST_ID_CANNOT_BE_EMPTY_ERROR: "آیدی پست نمیتواند خالی باشد",
  PROFILE_NOT_FOUND_ERROR: "پروفایل پیدا نشد",
  COMMENT_NOT_AVAILABLE_ERROR: "کامنت پیدا نشد",
  POST_ID_NOT_PROVIDED: "آیدی پست باید ارسال شود",
  HAVE_NOT_ANY_FOLLOWING: "شما کسی را فالو نکردید",
  HAVE_NOT_ANY_FOLLOWER: "کسی شما را فالو نکرده است",
  LIKE_ADDED_SUCCESSFULLY: "لایک با موفقیت اضافه شد",
  LIKE_REMOVED_SUCCESSFULLY: "لایک با موفقیت حذف شد",
  CAPTION: "کپشن",
  NAME: "نام",
  COMMENT: "کامنت",
  FOLLOW_NOTIFICATION_TITLE: (firstName: string, lastName: string) =>
    `${firstName} ${lastName} دنبالت کرد`,
  LIKE_NOTIFICATION_TITLE: (firstName: string, lastName: string) =>
    `${firstName} ${lastName} این عکس رو لایک کرده`,
  MENTION_NOTIFICATION_TITLE: (firstName: string, lastName: string) =>
    `${firstName} ${lastName} توی اون یکی عکس تگت کرده`,
  FOLLOW_REQUEST_NOTIFICATION_TITLE: (firstName: string, lastName: string) =>
    `${firstName} ${lastName} درخواست دوستی داده`,
  FOLLOW_REQUEST_RESULT_NOTIFICATION_TITLE: (
    firstName: string,
    lastName: string
  ) => `${firstName} ${lastName} درخواست دوستی‌ات رو قبول کرد`,
  INPUT_TOO_LONG_ERROR: (inputName: string, max: number) =>
    `${inputName} نمیتواند بیشتر از ${max} کاراکتر باشد`,
};
